plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version '2.7.1'
}

group 'com.mawl.mybatislog'
version '2.0.4'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/central/' }
    maven { url 'https://maven.aliyun.com/repository/public/' }
    maven { url 'https://maven.aliyun.com/repository/google/' }
    maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.14.0'
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    intellijPlatform {
        intellijIdeaCommunity('2025.1')
    }
}

intellijPlatform {
    pluginConfiguration {
        ideaVersion {
            sinceBuild = '251'
            untilBuild = provider { null }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
