plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '1.17.4'
}

group 'com.mawl.mybatislog'
version '2.0.2'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/central/' }
    maven { url 'https://maven.aliyun.com/repository/public/' }
    maven { url 'https://maven.aliyun.com/repository/google/' }
    maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
    mavenCentral()
}

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.14.0'
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
}

intellij {
    version = '2024.1'
    plugins = []
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

patchPluginXml {
    sinceBuild = '241'
    untilBuild = ''
    changeNotes = """
<dl>
    <dt><b>${project.version}</b></dt>
    <dd>Compatible with the latest IntelliJ IDEA versions</dd>
    <dd>Restore mybatis sql log to original whole executable sql</dd>
</dl>
      """
}

runIde {
    autoReloadPlugins = true
}
